apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx    
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 19061977/desafio-nginxnode_fc_nginx
          # command: ["tail","-f","/dev/null"]
          resources:
            requests: 
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-volume
      volumes:
        - name: nginx-volume
          configMap:
            name: nginx-config
