apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: ClusterIP
  # type: LoadBalancer
  ports:
  - name: nginx-service
    port: 80
    targetPort: 80
    protocol: TCP