apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
spec:
  selector:
    matchLabels:
      app: nodeserver    
<<<<<<< HEAD
  replicas: 2
=======
  replicas: 1
>>>>>>> 72ab13fc7b25f632a1f8d073498930a906b1fd7a
  template:
    metadata:
      labels:
        app: nodeserver
        version: A
    spec:
      containers:
        - name: nodeserver
          image: 19061977/desafio-nginxnode_fc_app
          # command: ["tail","-f","/dev/null"]
          env:
            - name: db_name
              value: mysql-h
            - name: user_db
              value: root
            - name: pass_db
              value: root

          resources:
            requests: 
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 25Mi
