apiVersion: v1
kind: Service
metadata:
  name: nodeserver-service
spec:
  selector:
    app: nodeserver
  # type: ClusterIP
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 3000
      nodePort: 30001
