apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: node-dr
spec:
  host: nodeserver-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "x-user"
  subsets:
    - name: all
      labels:
        app: nodeserver


---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: node-vs
spec:
  hosts:
  - nodeserver-service
  http:
    - route:
      - destination:
          host: nodeserver-service
          subset: all
   