---
- name: ISTIOCTL | Check installation
  stat:
    path: "{{ istioctl_binary_dir }}/istioctl"
  changed_when: False
  register: istioctl_binary

- name : Download Istio
  shell: curl -L {{ istioctl_mirror }} | sh -
  when: not istioctl_binary.stat.exists

- name : Add istio to a PATH 
  shell: cd {{ istioctl_binary_dir }} && export PATH=$PWD/bin:$PATH && istioctl install -y
  when: not istioctl_binary.stat.exists

- name: set istiod to a namespace default
  shell: kubectl label namespace default istio-injection=enabled
  when: not istioctl_binary.stat.exists