version: '3'

services:
  control:
    build: .
    image: marcelo/my_ubuntu:latest
    container_name: control
    command: [ "sh", "-c", "service ssh start ; tail -f /dev/null"]
    hostname: control
    volumes:
      - ./ansible:/root/ansible
      - ./ssh_Key:/root/.ssh

  # node1:
  #   image: marcelo/my_ubuntu:latest
  #   depends_on:
  #     - control
  #   container_name: node1
  #   command:  [ "sh", "-c", "service ssh start ; tail -f /dev/null"]
  #   hostname: node1
