name: CI_CD_Flow
on:
  pull_request:
    branches: 
      - master
      - developer

jobs:
  CI:
    name: ci-flow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        password: ${{ secrets.DOCKERHUB_PWD }}
        username: ${{ secrets.DOCKERHUB_USER }}
    - name: Build, push and run Node APP
      uses: docker/build-push-action@v2.6.1
      with:
        context: ./nginx
        file: ./nginx/Dockerfile
        push: true
        tags: 19061977/desafio-nginxnode_fc_nginx:latest
    - name: Build, push and run Node APP
      uses: docker/build-push-action@v2.6.1
      with:
        context: ./node
        file: ./node/Dockerfile
        push: true
        tags: 19061977/desafio-nginxnode_fc_app:latest

  CD:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [CI]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - name: Deploy MySql
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            k8s/mysql/mysql-initdb-config.yaml
            k8s/mysql/mysql-service-h.yaml
            k8s/mysql/mysql-statefulset.yaml
      - name: Deploy WEB
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            k8s/node_app/deployment.yaml
            k8s/node_app/service.yaml
          images: 19061977/desafio-nginxnode_fc_app:${{ github.run_number }}
